import { ServiceHubConfig } from "@/components/ServiceHubScreen";

export const SERVICE_HUB_CONFIGS: Record<string, ServiceHubConfig> = {
  cleaning: {
    key: "cleaning",
    headerTitle: "Home Services",
    heroTitle: "Cleaning And Home Care",
    heroSubtitle:
      "Choose deep cleaning, kitchen and bathroom detailing, and outdoor garden upkeep in one premium workflow.",
    heroGradient: ["#0F766E", "#0E7490"],
    accent: "#0F766E",
    quickInfo: [
      { id: "c-q1", label: "Avg Arrival", value: "45 min", icon: "time-outline" },
      { id: "c-q2", label: "Certified Team", value: "1,200+", icon: "shield-checkmark-outline" },
      { id: "c-q3", label: "Satisfaction", value: "4.8/5", icon: "star-outline" },
    ],
    promos: [
      {
        id: "c-p1",
        title: "Weekend Home Deep Clean",
        subtitle: "Book full-home cleaning + bathroom detailing and save 20%.",
        cta: "Claim Weekend Slot",
        route: "/special-offer",
        gradient: ["#0D9488", "#14B8A6"],
        image: "https://images.pexels.com/photos/4239148/pexels-photo-4239148.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "c-p2",
        title: "Garden Revival Pack",
        subtitle: "Lawn trim, pruning, and debris removal bundle at flat pricing.",
        cta: "View Bundle",
        route: "/special-offer",
        gradient: ["#15803D", "#22C55E"],
        image: "https://images.pexels.com/photos/4505170/pexels-photo-4505170.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "c-p3",
        title: "Kitchen + Bathroom Duo",
        subtitle: "Book both high-use areas together and reduce visit charges.",
        cta: "Book Duo",
        route: "/special-offer",
        gradient: ["#0891B2", "#06B6D4"],
        image: "https://images.pexels.com/photos/5854186/pexels-photo-5854186.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "c-p4",
        title: "Move-in Deep Reset",
        subtitle: "Complete cleaning package before shifting into a new home.",
        cta: "Plan Move-in Service",
        route: "/special-offer",
        gradient: ["#0F766E", "#0EA5A4"],
        image: "https://images.pexels.com/photos/4107281/pexels-photo-4107281.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "c-p5",
        title: "Festival Sanitization Week",
        subtitle: "Priority slots for full sanitization before family gatherings.",
        cta: "Reserve Priority Slot",
        route: "/special-offer",
        gradient: ["#0E7490", "#2563EB"],
        image: "https://images.pexels.com/photos/4108711/pexels-photo-4108711.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
    ],
    sections: [
      {
        id: "c-s1",
        title: "Home Cleaning Essentials",
        subtitle: "Day-to-day and deep cleaning tasks for every room.",
        gradient: ["#0F766E", "#0EA5A4"],
        items: [
          {
            id: "c-1",
            title: "Full Home Deep Cleaning",
            description: "Floors, furniture, dusting, fans, switches, and sanitization for all rooms.",
            duration: "4-6 hrs",
            price: 1499,
            icon: "home-outline",
            badge: "Popular",
            tags: ["Sanitization", "Pet-safe products", "Same-day"],
          },
          {
            id: "c-2",
            title: "Kitchen Degreasing Service",
            description: "Cabinets, chimney area, backsplash, slab, and sink deep degreasing.",
            duration: "2-3 hrs",
            price: 999,
            icon: "restaurant-outline",
            tags: ["Oil stain removal", "Steam clean", "Odor control"],
          },
          {
            id: "c-3",
            title: "Bathroom Hygiene Reset",
            description: "Tile scale removal, WC disinfection, mirror polish, and grout treatment.",
            duration: "90 min",
            price: 649,
            icon: "water-outline",
            tags: ["Hard water stains", "Mold treatment", "Disinfection"],
          },
          {
            id: "c-4",
            title: "Sofa And Carpet Shampoo",
            description: "Foam wash and extraction for couches, rugs, and heavy fabric carpets.",
            duration: "2 hrs",
            price: 1199,
            icon: "bed-outline",
            tags: ["Fabric safe", "Stain treatment", "Quick dry"],
          },
        ],
      },
      {
        id: "c-s2",
        title: "Outdoor And Garden Care",
        subtitle: "Complete upkeep for balconies, lawns, and terraces.",
        gradient: ["#166534", "#22C55E"],
        items: [
          {
            id: "c-5",
            title: "Lawn Mowing And Edge Trimming",
            description: "Mow grass uniformly, trim edges, and clear clippings for a clean finish.",
            duration: "75 min",
            price: 799,
            icon: "leaf-outline",
            tags: ["Lawn care", "Weed trim", "Waste collection"],
          },
          {
            id: "c-6",
            title: "Balcony And Patio Wash",
            description: "Pressure wash and scrub outdoor floors, rails, and corners.",
            duration: "60 min",
            price: 549,
            icon: "rainy-outline",
            tags: ["Pressure wash", "Dust removal", "Eco-cleaners"],
          },
          {
            id: "c-7",
            title: "Plant Pruning And Repotting",
            description: "Shape plants, remove dry leaves, and repot where needed.",
            duration: "90 min",
            price: 699,
            icon: "flower-outline",
            tags: ["Seasonal care", "Fertilizer guidance", "Home garden"],
          },
          {
            id: "c-8",
            title: "Bulk Waste Pickup",
            description: "Old cartons, dry leaves, and clutter pickup with disposal support.",
            duration: "45 min",
            price: 399,
            icon: "trash-outline",
            tags: ["Clutter clear", "Doorstep pickup", "Scheduled"],
          },
        ],
      },
    ],
    faqs: [
      {
        id: "c-f1",
        question: "Do I need to provide cleaning products?",
        answer: "No. Professionals carry branded supplies and equipment suitable for home use.",
      },
      {
        id: "c-f2",
        question: "Can I combine indoor cleaning with garden services?",
        answer: "Yes. Choose both tasks in one booking and you get optimized pricing and slots.",
      },
      {
        id: "c-f3",
        question: "How often should deep cleaning be done?",
        answer: "Most homes benefit from full deep cleaning every 8 to 12 weeks.",
      },
    ],
  },

  electrician: {
    key: "electrician",
    headerTitle: "Electrical",
    heroTitle: "Electrician And Safety Services",
    heroSubtitle:
      "From wiring and switchboard repairs to smart-home installations and safety checks.",
    heroGradient: ["#1D4ED8", "#4338CA"],
    accent: "#1D4ED8",
    quickInfo: [
      { id: "e-q1", label: "Avg Arrival", value: "35 min", icon: "flash-outline" },
      { id: "e-q2", label: "Licensed Pros", value: "980+", icon: "medal-outline" },
      { id: "e-q3", label: "Warranty", value: "30 days", icon: "shield-outline" },
    ],
    promos: [
      {
        id: "e-p1",
        title: "Power Safety Check",
        subtitle: "Book MCB panel + earthing inspection with discounted visit fee.",
        cta: "Book Safety Check",
        route: "/special-offer",
        gradient: ["#1D4ED8", "#2563EB"],
        image: "https://images.pexels.com/photos/4792479/pexels-photo-4792479.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "e-p2",
        title: "Smart Home Install",
        subtitle: "Upgrade switches, smart plugs, and app controls in one package.",
        cta: "Explore Smart Pack",
        route: "/special-offer",
        gradient: ["#0F766E", "#0EA5E9"],
        image: "https://images.pexels.com/photos/2577368/pexels-photo-2577368.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "e-p3",
        title: "Inverter Readiness Check",
        subtitle: "Pre-summer backup inspection with load balancing guidance.",
        cta: "Schedule Check",
        route: "/special-offer",
        gradient: ["#1E40AF", "#3B82F6"],
        image: "https://images.pexels.com/photos/1108572/pexels-photo-1108572.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "e-p4",
        title: "Lighting Upgrade Package",
        subtitle: "Replace old fixtures with efficient LED lighting setup.",
        cta: "Upgrade Lights",
        route: "/special-offer",
        gradient: ["#0EA5E9", "#0284C7"],
        image: "https://images.pexels.com/photos/112811/pexels-photo-112811.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "e-p5",
        title: "Switchboard Renewal Plan",
        subtitle: "Modern modular switchboards with clean rewiring support.",
        cta: "See Plan",
        route: "/special-offer",
        gradient: ["#1D4ED8", "#4338CA"],
        image: "https://images.pexels.com/photos/257736/pexels-photo-257736.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
    ],
    sections: [
      {
        id: "e-s1",
        title: "Repair And Installation",
        subtitle: "Electrical fixes and new point installations for homes.",
        gradient: ["#1D4ED8", "#4338CA"],
        items: [
          {
            id: "e-1",
            title: "Switchboard Repair",
            description: "Fix short circuits, sparking switches, and loose socket points.",
            duration: "45 min",
            price: 349,
            icon: "flash-outline",
            badge: "Fast",
            tags: ["Socket repair", "Sparking fix", "Same-day"],
          },
          {
            id: "e-2",
            title: "Fan Installation",
            description: "Ceiling fan mount, balancing, and regulator setup.",
            duration: "40 min",
            price: 299,
            icon: "speedometer-outline",
            tags: ["Mounting", "Wiring", "Functional check"],
          },
          {
            id: "e-3",
            title: "Decorative Lighting Setup",
            description: "Install wall lights, pendants, and strip lights for interiors.",
            duration: "60 min",
            price: 499,
            icon: "bulb-outline",
            tags: ["Ambient lights", "LED setup", "Fixture fitment"],
          },
          {
            id: "e-4",
            title: "Inverter And Battery Wiring",
            description: "Backup system connection and load balancing for outages.",
            duration: "75 min",
            price: 899,
            icon: "battery-charging-outline",
            tags: ["Backup power", "Surge safe", "Load test"],
          },
        ],
      },
      {
        id: "e-s2",
        title: "Safety And Diagnostics",
        subtitle: "Preventive checks and fault tracing before damage spreads.",
        gradient: ["#0369A1", "#0EA5E9"],
        items: [
          {
            id: "e-5",
            title: "MCB And DB Panel Inspection",
            description: "Thermal checks, labeling, and breaker health assessment.",
            duration: "50 min",
            price: 599,
            icon: "construct-outline",
            tags: ["Panel health", "Load audit", "Risk alerts"],
          },
          {
            id: "e-6",
            title: "Earthing And Leakage Test",
            description: "Earth resistance and leakage scan for safety compliance.",
            duration: "70 min",
            price: 749,
            icon: "shield-checkmark-outline",
            tags: ["Safety test", "Leakage scan", "Report"],
          },
          {
            id: "e-7",
            title: "Appliance Power Point Setup",
            description: "Dedicated points for AC, geyser, microwave, or washing machine.",
            duration: "60 min",
            price: 449,
            icon: "tv-outline",
            tags: ["Dedicated line", "Safe load", "Neat routing"],
          },
          {
            id: "e-8",
            title: "Smart Switch Upgrade",
            description: "Replace old switches with app-enabled and voice-ready modules.",
            duration: "80 min",
            price: 1099,
            icon: "phone-portrait-outline",
            tags: ["Automation", "App control", "Voice assistant"],
          },
        ],
      },
    ],
    faqs: [
      {
        id: "e-f1",
        question: "Do technicians carry spare switchboards and wiring?",
        answer: "Yes. Standard parts are available on-visit; premium parts are billed after approval.",
      },
      {
        id: "e-f2",
        question: "Can you fix sudden power trips?",
        answer: "Yes. Fault isolation and corrective repair are part of the standard visit.",
      },
      {
        id: "e-f3",
        question: "Is there a post-service warranty?",
        answer: "Most services include a 30-day workmanship warranty.",
      },
    ],
  },

  plumbing: {
    key: "plumbing",
    headerTitle: "Plumbing",
    heroTitle: "Plumbing And Water System Care",
    heroSubtitle:
      "Solve leakage, drainage, and fitting issues with experienced plumbers and transparent pricing.",
    heroGradient: ["#0284C7", "#06B6D4"],
    accent: "#0284C7",
    quickInfo: [
      { id: "p-q1", label: "Avg Arrival", value: "40 min", icon: "water-outline" },
      { id: "p-q2", label: "Jobs Completed", value: "25k+", icon: "checkmark-done-outline" },
      { id: "p-q3", label: "Repeat Rate", value: "72%", icon: "people-outline" },
    ],
    promos: [
      {
        id: "p-p1",
        title: "Leak Stop Express",
        subtitle: "Emergency leak repairs with priority same-day time windows.",
        cta: "Reserve Emergency Slot",
        route: "/special-offer",
        gradient: ["#0284C7", "#0EA5E9"],
        image: "https://images.pexels.com/photos/8486972/pexels-photo-8486972.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "p-p2",
        title: "Bathroom Upgrade Combo",
        subtitle: "Mixer, shower, and drain servicing in one optimized booking.",
        cta: "See Combo",
        route: "/special-offer",
        gradient: ["#0F766E", "#14B8A6"],
        image: "https://images.pexels.com/photos/8293725/pexels-photo-8293725.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "p-p3",
        title: "Kitchen Drain Rescue",
        subtitle: "Fast unclogging and odor-control package for busy kitchens.",
        cta: "Book Drain Rescue",
        route: "/special-offer",
        gradient: ["#0369A1", "#0284C7"],
        image: "https://images.pexels.com/photos/4246282/pexels-photo-4246282.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "p-p4",
        title: "Tank Hygiene Special",
        subtitle: "Seasonal tank cleaning and outlet sanitization discount.",
        cta: "Book Tank Service",
        route: "/special-offer",
        gradient: ["#0E7490", "#06B6D4"],
        image: "https://images.pexels.com/photos/5691512/pexels-photo-5691512.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "p-p5",
        title: "Whole-home Water Audit",
        subtitle: "Leakage and pressure health check across all pipelines.",
        cta: "Start Audit",
        route: "/special-offer",
        gradient: ["#0EA5E9", "#2563EB"],
        image: "https://images.pexels.com/photos/4792485/pexels-photo-4792485.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
    ],
    sections: [
      {
        id: "p-s1",
        title: "Leak And Fixture Repairs",
        subtitle: "Quick repair for taps, joints, and washroom fixtures.",
        gradient: ["#0369A1", "#0EA5E9"],
        items: [
          {
            id: "p-1",
            title: "Pipe Leakage Repair",
            description: "Fix concealed and external pipeline leakage points.",
            duration: "60 min",
            price: 449,
            icon: "water-outline",
            badge: "High Demand",
            tags: ["Leak trace", "Joint seal", "Pressure check"],
          },
          {
            id: "p-2",
            title: "Tap And Faucet Service",
            description: "Resolve dripping taps and cartridge replacement.",
            duration: "35 min",
            price: 249,
            icon: "construct-outline",
            tags: ["Tap fix", "Drip stop", "Spare fitment"],
          },
          {
            id: "p-3",
            title: "Shower And Mixer Installation",
            description: "Install and align bathroom mixers and shower kits.",
            duration: "50 min",
            price: 399,
            icon: "hand-left-outline",
            tags: ["Hot-cold mix", "Alignment", "Flow test"],
          },
          {
            id: "p-4",
            title: "Drain Unclogging",
            description: "Kitchen and bathroom drain unclogging with cleanup.",
            duration: "45 min",
            price: 299,
            icon: "funnel-outline",
            tags: ["Drain cleaning", "Odor reduction", "Flow restore"],
          },
        ],
      },
      {
        id: "p-s2",
        title: "Water System Maintenance",
        subtitle: "Pump, tank, and geyser related plumbing support.",
        gradient: ["#0E7490", "#06B6D4"],
        items: [
          {
            id: "p-5",
            title: "Water Tank Cleaning",
            description: "Mechanical scrub + anti-bacterial treatment for tanks.",
            duration: "90 min",
            price: 999,
            icon: "water",
            tags: ["Tank hygiene", "Safe chemical", "Sediment removal"],
          },
          {
            id: "p-6",
            title: "Motor Pump Installation",
            description: "Install and test domestic pressure and overhead pumps.",
            duration: "80 min",
            price: 899,
            icon: "flash-outline",
            tags: ["Pump fitment", "Wiring check", "Pressure setup"],
          },
          {
            id: "p-7",
            title: "Geyser Inlet Outlet Fix",
            description: "Inlet/outlet leakage, connection, and valve servicing.",
            duration: "55 min",
            price: 499,
            icon: "flame-outline",
            tags: ["Safety valve", "No leak", "Flow balanced"],
          },
          {
            id: "p-8",
            title: "Pipeline Route Inspection",
            description: "End-to-end line check for pressure drop and seepage.",
            duration: "70 min",
            price: 649,
            icon: "trail-sign-outline",
            tags: ["Inspection", "Root cause", "Service report"],
          },
        ],
      },
    ],
    faqs: [
      {
        id: "p-f1",
        question: "Can I book emergency plumbing for active leaks?",
        answer: "Yes, emergency slots are prioritized for active water leakage jobs.",
      },
      {
        id: "p-f2",
        question: "Are spare parts included in listed pricing?",
        answer: "Service fee is included; required parts are quoted and approved before replacement.",
      },
      {
        id: "p-f3",
        question: "Do you support apartments and villas both?",
        answer: "Yes, teams are equipped for both small and large residential properties.",
      },
    ],
  },

  acRepair: {
    key: "acRepair",
    headerTitle: "Cooling",
    heroTitle: "AC Repair And Cooling Maintenance",
    heroSubtitle:
      "Handle low cooling, gas refill, installation, and preventive maintenance before summer peak.",
    heroGradient: ["#0EA5E9", "#2563EB"],
    accent: "#0EA5E9",
    quickInfo: [
      { id: "a-q1", label: "Avg Arrival", value: "55 min", icon: "snow-outline" },
      { id: "a-q2", label: "Serviced Units", value: "18k+", icon: "hardware-chip-outline" },
      { id: "a-q3", label: "Cooling Recovery", value: "92%", icon: "analytics-outline" },
    ],
    promos: [
      {
        id: "a-p1",
        title: "Summer Cooling Prep",
        subtitle: "AC service + deep coil cleaning + filter wash at combo pricing.",
        cta: "Book Cooling Prep",
        route: "/special-offer",
        gradient: ["#0EA5E9", "#3B82F6"],
        image: "https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "a-p2",
        title: "Annual Maintenance Plan",
        subtitle: "Two preventive visits, priority support, and discounted repairs.",
        cta: "View AMC",
        route: "/special-offer",
        gradient: ["#1D4ED8", "#4338CA"],
        image: "https://images.pexels.com/photos/5691643/pexels-photo-5691643.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "a-p3",
        title: "Low Cooling Quick Fix",
        subtitle: "Rapid diagnosis and tune-up for sudden cooling drop.",
        cta: "Get Quick Fix",
        route: "/special-offer",
        gradient: ["#0284C7", "#0EA5E9"],
        image: "https://images.pexels.com/photos/4483610/pexels-photo-4483610.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "a-p4",
        title: "AC Shift And Refit",
        subtitle: "Relocation-ready dismantle, transport prep, and reinstall plan.",
        cta: "Plan Shift",
        route: "/special-offer",
        gradient: ["#1D4ED8", "#2563EB"],
        image: "https://images.pexels.com/photos/4792479/pexels-photo-4792479.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "a-p5",
        title: "Monsoon Protection Add-on",
        subtitle: "Outdoor unit anti-rust and drain protection seasonal offer.",
        cta: "Add Protection",
        route: "/special-offer",
        gradient: ["#0369A1", "#3B82F6"],
        image: "https://images.pexels.com/photos/4254168/pexels-photo-4254168.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
    ],
    sections: [
      {
        id: "a-s1",
        title: "Core AC Services",
        subtitle: "Repair and maintenance for split, window, and inverter units.",
        gradient: ["#0EA5E9", "#3B82F6"],
        items: [
          {
            id: "a-1",
            title: "AC General Service",
            description: "Filter wash, coil dust removal, drain line check, and performance test.",
            duration: "90 min",
            price: 699,
            icon: "snow-outline",
            badge: "Best Value",
            tags: ["Performance boost", "Airflow check", "Seasonal"],
          },
          {
            id: "a-2",
            title: "Gas Refill And Leak Check",
            description: "Leak test and refrigerant refill based on pressure requirement.",
            duration: "2 hrs",
            price: 1699,
            icon: "thermometer-outline",
            tags: ["Leak tracing", "Refill", "Pressure tested"],
          },
          {
            id: "a-3",
            title: "Low Cooling Diagnosis",
            description: "Fix weak cooling due to compressor, capacitor, or gas issues.",
            duration: "75 min",
            price: 549,
            icon: "speedometer-outline",
            tags: ["Root cause", "Repair", "Output test"],
          },
          {
            id: "a-4",
            title: "AC Noise And Vibration Fix",
            description: "Address rattling sounds and indoor unit vibration problems.",
            duration: "60 min",
            price: 499,
            icon: "volume-high-outline",
            tags: ["Stabilization", "Panel tuning", "Silent run"],
          },
        ],
      },
      {
        id: "a-s2",
        title: "Installation And Upgrades",
        subtitle: "Mounting, shifting, and accessory setup for better cooling.",
        gradient: ["#1D4ED8", "#2563EB"],
        items: [
          {
            id: "a-5",
            title: "Split AC Installation",
            description: "Indoor/outdoor mounting, piping, and live functional checks.",
            duration: "2.5 hrs",
            price: 1699,
            icon: "construct-outline",
            tags: ["Mounting", "Copper line", "Commissioning"],
          },
          {
            id: "a-6",
            title: "Window AC Installation",
            description: "Bracket fitment, leveling, and secure power setup.",
            duration: "90 min",
            price: 1199,
            icon: "apps-outline",
            tags: ["Secure fit", "Drain slope", "Power safety"],
          },
          {
            id: "a-7",
            title: "AC Shift And Reinstallation",
            description: "Safe dismantle, transport-ready prep, and reinstall at new location.",
            duration: "3 hrs",
            price: 2299,
            icon: "swap-horizontal-outline",
            tags: ["Dismantle", "Reinstall", "Gas-safe handling"],
          },
          {
            id: "a-8",
            title: "Anti-rust And Drain Protection",
            description: "Preventive treatment for outdoor unit corrosion and pipe clogging.",
            duration: "45 min",
            price: 399,
            icon: "shield-checkmark-outline",
            tags: ["Protective coat", "Drain guard", "Long life"],
          },
        ],
      },
    ],
    faqs: [
      {
        id: "a-f1",
        question: "How often should AC be serviced?",
        answer: "Before summer and mid-season is ideal for consistent cooling and lower electricity usage.",
      },
      {
        id: "a-f2",
        question: "Do you provide installation materials?",
        answer: "Standard consumables are available; extra piping and brackets are billed as required.",
      },
      {
        id: "a-f3",
        question: "Can I book AMC from this page?",
        answer: "Yes, choose annual maintenance offer and complete booking in one flow.",
      },
    ],
  },

  mensSalon: {
    key: "mensSalon",
    headerTitle: "Men Salon",
    heroTitle: "Mens Grooming And Salon At Home",
    heroSubtitle:
      "Hair, beard, cleanup, and premium grooming delivered by trained male grooming experts.",
    heroGradient: ["#312E81", "#4F46E5"],
    accent: "#4F46E5",
    quickInfo: [
      { id: "m-q1", label: "Avg Visit", value: "60 min", icon: "time-outline" },
      { id: "m-q2", label: "Top Stylists", value: "420+", icon: "person-outline" },
      { id: "m-q3", label: "Repeat Users", value: "68%", icon: "refresh-outline" },
    ],
    promos: [
      {
        id: "m-p1",
        title: "Haircut + Beard Combo",
        subtitle: "Most-booked package for office-ready and event-ready grooming.",
        cta: "Book Combo",
        route: "/special-offer",
        gradient: ["#4F46E5", "#7C3AED"],
        image: "https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "m-p2",
        title: "Wedding Season Groom Pack",
        subtitle: "Cleanup, de-tan, beard styling, and hair styling in one slot.",
        cta: "View Groom Pack",
        route: "/special-offer",
        gradient: ["#0F172A", "#334155"],
        image: "https://images.pexels.com/photos/3992879/pexels-photo-3992879.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "m-p3",
        title: "Express Office Grooming",
        subtitle: "30-minute sharp look package for weekdays and meetings.",
        cta: "Book Express",
        route: "/special-offer",
        gradient: ["#312E81", "#4F46E5"],
        image: "https://images.pexels.com/photos/3998393/pexels-photo-3998393.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "m-p4",
        title: "Premium Facial Add-on",
        subtitle: "Quick facial treatment bundled with any haircut service.",
        cta: "Add Facial",
        route: "/special-offer",
        gradient: ["#1E1B4B", "#312E81"],
        image: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "m-p5",
        title: "Head Massage Saver",
        subtitle: "Oil massage add-on at discounted price with grooming combos.",
        cta: "Claim Add-on",
        route: "/special-offer",
        gradient: ["#3730A3", "#6366F1"],
        image: "https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
    ],
    sections: [
      {
        id: "m-s1",
        title: "Hair And Beard Services",
        subtitle: "Core grooming services for regular maintenance.",
        gradient: ["#4338CA", "#6366F1"],
        items: [
          {
            id: "m-1",
            title: "Classic Haircut",
            description: "Consultation-based haircut with finishing and style advice.",
            duration: "40 min",
            price: 299,
            icon: "cut-outline",
            image: "https://images.pexels.com/photos/1813272/pexels-photo-1813272.jpeg?auto=compress&cs=tinysrgb&w=1200",
            badge: "Top Rated",
            tags: ["Scissor + clipper", "Styling", "Neat finish"],
          },
          {
            id: "m-2",
            title: "Beard Trim And Shape",
            description: "Precision beard line-up and shape correction.",
            duration: "30 min",
            price: 199,
            icon: "brush-outline",
            image: "https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Sharp lines", "Symmetry", "Trimmer hygiene"],
          },
          {
            id: "m-3",
            title: "Haircut + Beard Combo",
            description: "Complete grooming combo at bundled pricing.",
            duration: "55 min",
            price: 449,
            icon: "sparkles-outline",
            image: "https://images.pexels.com/photos/3998393/pexels-photo-3998393.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Value pack", "Quick", "Event ready"],
          },
          {
            id: "m-4",
            title: "Head Massage",
            description: "Pressure-point based oil massage for scalp relaxation.",
            duration: "25 min",
            price: 249,
            icon: "hand-left-outline",
            image: "https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Stress relief", "Oil options", "Scalp care"],
          },
        ],
      },
      {
        id: "m-s2",
        title: "Skin And Finishing",
        subtitle: "Facial cleanup and premium finishing for special occasions.",
        gradient: ["#1E1B4B", "#312E81"],
        items: [
          {
            id: "m-5",
            title: "Detan Cleanup",
            description: "Tan reduction with scrub and mask tailored to skin type.",
            duration: "35 min",
            price: 399,
            icon: "sunny-outline",
            image: "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Tan control", "Glow finish", "Hydration"],
          },
          {
            id: "m-6",
            title: "Express Facial",
            description: "Cleansing, exfoliation, and glow mask for instant freshness.",
            duration: "40 min",
            price: 499,
            icon: "happy-outline",
            image: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Party ready", "Skin refresh", "Quick"],
          },
          {
            id: "m-7",
            title: "Hair Styling Finish",
            description: "Modern hold styling and final setting for events.",
            duration: "20 min",
            price: 199,
            icon: "color-wand-outline",
            image: "https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Event styling", "Hold products", "Custom look"],
          },
          {
            id: "m-8",
            title: "Premium Groom Package",
            description: "Haircut, beard, cleanup, and head massage in one session.",
            duration: "90 min",
            price: 999,
            icon: "medal-outline",
            image: "https://images.pexels.com/photos/3998393/pexels-photo-3998393.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["All-in-one", "Premium", "Most complete"],
          },
        ],
      },
    ],
    faqs: [
      {
        id: "m-f1",
        question: "Can I choose a preferred stylist?",
        answer: "Yes, preferred stylist option is available during final booking step.",
      },
      {
        id: "m-f2",
        question: "Are hygiene kits used per customer?",
        answer: "Yes, sanitized tools and single-use items are used for each appointment.",
      },
      {
        id: "m-f3",
        question: "Is there a combo package with facial included?",
        answer: "Yes, premium groom package includes facial, haircut, beard, and massage.",
      },
    ],
  },

  womensSalon: {
    key: "womensSalon",
    headerTitle: "Women Salon",
    heroTitle: "Womens Beauty And Salon Services",
    heroSubtitle:
      "Hair, skin, makeup, and nail services delivered with premium hygiene and expert beauticians.",
    heroGradient: ["#BE185D", "#EC4899"],
    accent: "#DB2777",
    quickInfo: [
      { id: "w-q1", label: "Avg Visit", value: "75 min", icon: "time-outline" },
      { id: "w-q2", label: "Beauty Experts", value: "530+", icon: "rose-outline" },
      { id: "w-q3", label: "Avg Rating", value: "4.9/5", icon: "star-outline" },
    ],
    promos: [
      {
        id: "w-p1",
        title: "Glow Facial Week",
        subtitle: "Hydra facial, cleanup, and glow mask with 25% off this week.",
        cta: "Book Glow Slot",
        route: "/special-offer",
        gradient: ["#BE185D", "#EC4899"],
        image: "https://images.pexels.com/photos/3997993/pexels-photo-3997993.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "w-p2",
        title: "Bridal Preview Session",
        subtitle: "Hair + makeup trial with expert consultation for events.",
        cta: "Explore Bridal",
        route: "/special-offer",
        gradient: ["#A21CAF", "#D946EF"],
        image: "https://images.pexels.com/photos/286763/pexels-photo-286763.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "w-p3",
        title: "Hair Spa Plus Styling",
        subtitle: "Repair-focused hair spa with event styling finish.",
        cta: "Book Hair Spa",
        route: "/special-offer",
        gradient: ["#DB2777", "#EC4899"],
        image: "https://images.pexels.com/photos/3997984/pexels-photo-3997984.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "w-p4",
        title: "Nail And Pedi Luxe Pack",
        subtitle: "Manicure and pedicure combo with premium finishing.",
        cta: "View Luxe Pack",
        route: "/special-offer",
        gradient: ["#A21CAF", "#C026D3"],
        image: "https://images.pexels.com/photos/3993441/pexels-photo-3993441.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "w-p5",
        title: "Waxing Combo Week",
        subtitle: "Arms and legs combo with soothing post-care included.",
        cta: "Book Combo",
        route: "/special-offer",
        gradient: ["#BE185D", "#F472B6"],
        image: "https://images.pexels.com/photos/458766/pexels-photo-458766.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
    ],
    sections: [
      {
        id: "w-s1",
        title: "Hair And Makeup",
        subtitle: "Popular beauty services for regular and event needs.",
        gradient: ["#BE185D", "#EC4899"],
        items: [
          {
            id: "w-1",
            title: "Haircut And Styling",
            description: "Face-shape based cut with blow-dry finishing.",
            duration: "50 min",
            price: 499,
            icon: "cut-outline",
            image: "https://images.pexels.com/photos/3997984/pexels-photo-3997984.jpeg?auto=compress&cs=tinysrgb&w=1200",
            badge: "Popular",
            tags: ["Consultation", "Blow dry", "Style finish"],
          },
          {
            id: "w-2",
            title: "Global Hair Color",
            description: "Premium color application with post-color treatment.",
            duration: "2 hrs",
            price: 1999,
            icon: "color-palette-outline",
            image: "https://images.pexels.com/photos/853427/pexels-photo-853427.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Ammonia-safe options", "Tone match", "Aftercare"],
          },
          {
            id: "w-3",
            title: "Party Makeup",
            description: "High-definition makeup with setting and touch-up kit.",
            duration: "75 min",
            price: 1499,
            icon: "color-wand-outline",
            image: "https://images.pexels.com/photos/286763/pexels-photo-286763.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["HD base", "Eye styling", "Long hold"],
          },
          {
            id: "w-4",
            title: "Bridal Makeup Trial",
            description: "Complete trial with look planning and shade selection.",
            duration: "90 min",
            price: 2499,
            icon: "diamond-outline",
            image: "https://images.pexels.com/photos/853441/pexels-photo-853441.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Consultation", "Trial look", "Event prep"],
          },
        ],
      },
      {
        id: "w-s2",
        title: "Skin And Nail Care",
        subtitle: "Facials, cleanups, waxing, and manicure-pedicure options.",
        gradient: ["#A21CAF", "#D946EF"],
        items: [
          {
            id: "w-5",
            title: "Hydra Facial",
            description: "Deep hydration and pore care for radiant skin.",
            duration: "60 min",
            price: 1199,
            icon: "water-outline",
            image: "https://images.pexels.com/photos/3997993/pexels-photo-3997993.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Hydration", "Glow", "Sensitive-skin friendly"],
          },
          {
            id: "w-6",
            title: "Cleanup And De-tan",
            description: "Cleanup with exfoliation and tan reduction routine.",
            duration: "45 min",
            price: 699,
            icon: "sunny-outline",
            image: "https://images.pexels.com/photos/3762664/pexels-photo-3762664.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Tan reduction", "Skin refresh", "Quick"],
          },
          {
            id: "w-7",
            title: "Manicure And Pedicure",
            description: "Nail shaping, cuticle care, scrub, and polish finish.",
            duration: "55 min",
            price: 799,
            icon: "hand-left-outline",
            image: "https://images.pexels.com/photos/3993441/pexels-photo-3993441.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Nail care", "Spa massage", "Polish"],
          },
          {
            id: "w-8",
            title: "Waxing Combo",
            description: "Arms, underarms, and legs waxing with soothing gel.",
            duration: "60 min",
            price: 999,
            icon: "flower-outline",
            image: "https://images.pexels.com/photos/458766/pexels-photo-458766.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Hygienic", "Gentle strips", "Combo savings"],
          },
        ],
      },
    ],
    faqs: [
      {
        id: "w-f1",
        question: "Can I customize bridal makeup packages?",
        answer: "Yes, trial and final booking packages can be customized by event type.",
      },
      {
        id: "w-f2",
        question: "Do you support sensitive skin products?",
        answer: "Yes, hypoallergenic product options are available on request.",
      },
      {
        id: "w-f3",
        question: "Are premium brand products included?",
        answer: "Standard premium products are included; brand-specific upgrades are optional.",
      },
    ],
  },

  massageSpa: {
    key: "massageSpa",
    headerTitle: "Massage And Spa",
    heroTitle: "Relaxation And Wellness Therapy",
    heroSubtitle:
      "Book stress-relief massages, deep tissue sessions, and wellness add-ons with trained therapists.",
    heroGradient: ["#9333EA", "#DB2777"],
    accent: "#9333EA",
    quickInfo: [
      { id: "s-q1", label: "Avg Session", value: "60 min", icon: "time-outline" },
      { id: "s-q2", label: "Therapists", value: "350+", icon: "heart-outline" },
      { id: "s-q3", label: "Relax Score", value: "4.9/5", icon: "sparkles-outline" },
    ],
    promos: [
      {
        id: "s-p1",
        title: "Weekend Stress Reset",
        subtitle: "Deep tissue + head massage combo for full-body relief.",
        cta: "Book Therapy",
        route: "/special-offer",
        gradient: ["#9333EA", "#C026D3"],
        image: "https://images.pexels.com/photos/3865792/pexels-photo-3865792.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "s-p2",
        title: "Couple Spa Slots",
        subtitle: "Parallel home sessions with special two-person pricing.",
        cta: "View Slots",
        route: "/special-offer",
        gradient: ["#DB2777", "#F43F5E"],
        image: "https://images.pexels.com/photos/6628790/pexels-photo-6628790.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "s-p3",
        title: "Aromatherapy Evening",
        subtitle: "Relaxing oil therapy package designed for evening recovery.",
        cta: "Reserve Evening Slot",
        route: "/special-offer",
        gradient: ["#9333EA", "#A855F7"],
        image: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "s-p4",
        title: "Hot Stone Upgrade",
        subtitle: "Add premium heat therapy to any selected massage plan.",
        cta: "Add Hot Stone",
        route: "/special-offer",
        gradient: ["#BE185D", "#EC4899"],
        image: "https://images.pexels.com/photos/275768/pexels-photo-275768.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "s-p5",
        title: "Sleep Recovery Night",
        subtitle: "Calming therapy sequence for better sleep and recovery.",
        cta: "Book Night Session",
        route: "/special-offer",
        gradient: ["#7E22CE", "#9333EA"],
        image: "https://images.pexels.com/photos/935743/pexels-photo-935743.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
    ],
    sections: [
      {
        id: "s-s1",
        title: "Core Massage Therapies",
        subtitle: "Relief and recovery focused massage formats.",
        gradient: ["#9333EA", "#C026D3"],
        items: [
          {
            id: "s-1",
            title: "Swedish Relaxation Massage",
            description: "Gentle pressure therapy to reduce stress and improve circulation.",
            duration: "60 min",
            price: 1199,
            icon: "body-outline",
            image: "https://images.pexels.com/photos/3865792/pexels-photo-3865792.jpeg?auto=compress&cs=tinysrgb&w=1200",
            badge: "Most Booked",
            tags: ["Relaxation", "Full body", "Aroma oils"],
          },
          {
            id: "s-2",
            title: "Deep Tissue Massage",
            description: "Targeted pressure for muscle knots and chronic stiffness.",
            duration: "75 min",
            price: 1599,
            icon: "fitness-outline",
            image: "https://images.pexels.com/photos/6628790/pexels-photo-6628790.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Pain relief", "Muscle recovery", "Sports friendly"],
          },
          {
            id: "s-3",
            title: "Back And Shoulder Therapy",
            description: "Focused upper-body session for desk-job fatigue.",
            duration: "45 min",
            price: 899,
            icon: "walk-outline",
            image: "https://images.pexels.com/photos/3757952/pexels-photo-3757952.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Posture relief", "Neck support", "Desk fatigue"],
          },
          {
            id: "s-4",
            title: "Head And Foot Reflex Massage",
            description: "Head pressure points and foot reflex zones for calming recovery.",
            duration: "40 min",
            price: 699,
            icon: "medical-outline",
            image: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Reflex points", "Sleep support", "Light pressure"],
          },
        ],
      },
      {
        id: "s-s2",
        title: "Spa Add-ons And Wellness",
        subtitle: "Enhance therapy sessions with spa rituals and upgrades.",
        gradient: ["#BE185D", "#EC4899"],
        items: [
          {
            id: "s-5",
            title: "Aromatherapy Upgrade",
            description: "Therapeutic essential oil blend customized for your session.",
            duration: "15 min",
            price: 299,
            icon: "flower-outline",
            image: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Lavender", "Stress relief", "Mood uplift"],
          },
          {
            id: "s-6",
            title: "Hot Stone Add-on",
            description: "Heat-based muscle release for deep relaxation.",
            duration: "20 min",
            price: 399,
            icon: "flame-outline",
            image: "https://images.pexels.com/photos/275768/pexels-photo-275768.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Heat therapy", "Back focus", "Deep release"],
          },
          {
            id: "s-7",
            title: "Sleep Recovery Session",
            description: "Low-light calming routine + light pressure massage plan.",
            duration: "50 min",
            price: 999,
            icon: "moon-outline",
            image: "https://images.pexels.com/photos/935743/pexels-photo-935743.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Sleep routine", "Nervous system calm", "Night package"],
          },
          {
            id: "s-8",
            title: "Couple Massage At Home",
            description: "Two synchronized sessions with curated relaxation music.",
            duration: "60 min",
            price: 2099,
            icon: "heart-half-outline",
            image: "https://images.pexels.com/photos/1029604/pexels-photo-1029604.jpeg?auto=compress&cs=tinysrgb&w=1200",
            tags: ["Dual session", "Private setup", "Premium"],
          },
        ],
      },
    ],
    faqs: [
      {
        id: "s-f1",
        question: "Are therapists professionally trained?",
        answer: "Yes, all therapists are certified and background verified.",
      },
      {
        id: "s-f2",
        question: "Can I request male or female therapist preference?",
        answer: "Yes, therapist preference is available during final booking.",
      },
      {
        id: "s-f3",
        question: "What space setup is needed at home?",
        answer: "A clean 6x6 area is enough; therapist carries required essentials.",
      },
    ],
  },

  applianceRepair: {
    key: "applianceRepair",
    headerTitle: "Appliance Repair",
    heroTitle: "Home Appliance Repair Hub",
    heroSubtitle:
      "Diagnose and fix refrigerator, washing machine, microwave, TV, and kitchen appliance issues quickly.",
    heroGradient: ["#2563EB", "#4F46E5"],
    accent: "#2563EB",
    quickInfo: [
      { id: "ar-q1", label: "Avg Arrival", value: "50 min", icon: "timer-outline" },
      { id: "ar-q2", label: "Technicians", value: "760+", icon: "construct-outline" },
      { id: "ar-q3", label: "First-Fix", value: "85%", icon: "checkmark-circle-outline" },
    ],
    promos: [
      {
        id: "ar-p1",
        title: "Kitchen Appliance Care",
        subtitle: "Mixer, chimney, microwave, and purifier maintenance bundle.",
        cta: "Book Kitchen Pack",
        route: "/special-offer",
        gradient: ["#2563EB", "#3B82F6"],
        image: "https://images.pexels.com/photos/6990498/pexels-photo-6990498.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "ar-p2",
        title: "AC + Fridge Combo Visit",
        subtitle: "Book cooling appliances in one visit and save on travel charge.",
        cta: "See Combo",
        route: "/special-offer",
        gradient: ["#1D4ED8", "#06B6D4"],
        image: "https://images.pexels.com/photos/9462630/pexels-photo-9462630.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "ar-p3",
        title: "Washing Machine Rescue",
        subtitle: "No-spin and drainage issue package with quick diagnosis.",
        cta: "Book Laundry Repair",
        route: "/special-offer",
        gradient: ["#1D4ED8", "#3B82F6"],
        image: "https://images.pexels.com/photos/4792479/pexels-photo-4792479.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "ar-p4",
        title: "Microwave Quick Service",
        subtitle: "Heating and control-panel issues fixed with priority slots.",
        cta: "Book Microwave Fix",
        route: "/special-offer",
        gradient: ["#2563EB", "#0EA5E9"],
        image: "https://images.pexels.com/photos/5691643/pexels-photo-5691643.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
      {
        id: "ar-p5",
        title: "TV And Entertainment Care",
        subtitle: "Display and sound diagnostics bundle for smart TVs.",
        cta: "Book TV Care",
        route: "/special-offer",
        gradient: ["#1E40AF", "#2563EB"],
        image: "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=1200",
      },
    ],
    sections: [
      {
        id: "ar-s1",
        title: "Cooling And Laundry Appliances",
        subtitle: "Repair for high-usage home appliances.",
        gradient: ["#2563EB", "#4F46E5"],
        items: [
          {
            id: "ar-1",
            title: "Refrigerator Repair",
            description: "Cooling faults, gas leakage checks, compressor and sensor issues.",
            duration: "70 min",
            price: 549,
            icon: "snow-outline",
            badge: "Most Requested",
            tags: ["Cooling fix", "Gas check", "Compressor diagnosis"],
          },
          {
            id: "ar-2",
            title: "Washing Machine Service",
            description: "No-spin, drain blockage, vibration, and inlet problems.",
            duration: "65 min",
            price: 499,
            icon: "refresh-outline",
            tags: ["Drum check", "Drain fix", "Auto mode diagnostics"],
          },
          {
            id: "ar-3",
            title: "AC Appliance Diagnostics",
            description: "Cooling appliance electrical and control board diagnosis.",
            duration: "60 min",
            price: 599,
            icon: "thermometer-outline",
            tags: ["Board check", "Sensor test", "Performance"],
          },
          {
            id: "ar-4",
            title: "Water Purifier Servicing",
            description: "RO filter and membrane check, leakage and pressure tuning.",
            duration: "50 min",
            price: 449,
            icon: "water-outline",
            tags: ["Filter check", "Membrane test", "Water quality"],
          },
        ],
      },
      {
        id: "ar-s2",
        title: "Kitchen And Entertainment Appliances",
        subtitle: "Small and large appliance repair for daily convenience.",
        gradient: ["#1D4ED8", "#0EA5E9"],
        items: [
          {
            id: "ar-5",
            title: "Microwave Oven Repair",
            description: "Heating coil, turntable, and control panel fixes.",
            duration: "55 min",
            price: 449,
            icon: "flame-outline",
            tags: ["Heating issue", "Panel controls", "Door sensor"],
          },
          {
            id: "ar-6",
            title: "TV Repair",
            description: "Display, sound, HDMI port, and motherboard troubleshooting.",
            duration: "70 min",
            price: 699,
            icon: "tv-outline",
            tags: ["LED/LCD", "Audio fix", "Port repair"],
          },
          {
            id: "ar-7",
            title: "Chimney And Hob Service",
            description: "Filter cleaning, suction check, ignition and burner care.",
            duration: "60 min",
            price: 599,
            icon: "flask-outline",
            tags: ["Grease clean", "Suction test", "Gas-safe"],
          },
          {
            id: "ar-8",
            title: "Mixer Grinder Repair",
            description: "Motor, blade coupling, and noise issue repair.",
            duration: "45 min",
            price: 349,
            icon: "settings-outline",
            tags: ["Motor check", "Blade fit", "Noise reduction"],
          },
        ],
      },
    ],
    faqs: [
      {
        id: "ar-f1",
        question: "Do you provide original spare parts?",
        answer: "Yes, genuine or brand-compatible parts are used based on availability.",
      },
      {
        id: "ar-f2",
        question: "Can multiple appliances be checked in one visit?",
        answer: "Yes, multi-appliance visits are supported with optimized visit charges.",
      },
      {
        id: "ar-f3",
        question: "Is diagnostic fee adjustable in final billing?",
        answer: "In most cases, diagnostic fee is adjusted against approved repair work.",
      },
    ],
  },
};
